### ISSUE TITLE
Some suggestions

### ISSUE THREAD

**Issue by satorope** [mojaveexpressguide/mojaveexpressguide.github.io#1]
I learned about this guide from The Sands created by Qolore7. It is excellent.
I would like to point out a few things.

MEG - Content
Another Millenia
Wrong file name.

MEG - Visuals
Power Armor Visual Enhancement (PAVE)
As with WSG, it would be better to rename OutfitGO.nif to OutfitArmyGO.nif.

MEG - Animations
Diagonal Movement
DiaMoveNVSE Patched used in The Sands would be better.
https://www.nexusmods.com/newvegas/mods/78534

**Comment by mojaveexpressguide** [comment]
Thanks for the suggestions.

I've fixed Another Millenia names.

The PAVE change isn't necessary for base FNV.

I prefer diagonal movement especially for its compatibility with 360 movement that I will likely add.

**Comment by satorope** [comment]
I see. I understand.
