### ISSUE TITLE
Weapon Texture Guide

### ISSUE THREAD

**Issue by satorope** [mojaveexpressguide/mojaveexpressguide.github.io#2]
Hello, I would like to comment on the Weapon Texture Guide.

Shovel and Friend
Wrong link.

WAP Year One and Bonus
This does not include the following three items, which must be added individually

Laser Rifle Rebirth
https://www.nexusmods.com/newvegas/mods/72759/
https://www.nexusmods.com/newvegas/mods/81963/

WAP 12.7 SMG Rebirth
https://www.nexusmods.com/newvegas/mods/73194/
https://www.nexusmods.com/newvegas/mods/79672/

WAP Gauss Rifle
https://www.nexusmods.com/newvegas/mods/76421/
https://www.nexusmods.com/newvegas/mods/79825/

And new
WAP Single Shotgun
https://www.nexusmods.com/newvegas/mods/83112

What about these textures?
Euclid's C-Finder Retexture
https://www.nexusmods.com/newvegas/mods/68624
Sonic emitter - Retextured
https://www.nexusmods.com/newvegas/mods/72909
BB Gun ReTexture
https://www.nexusmods.com/newvegas/mods/67445

**Comment by mojaveexpressguide** [comment]
Thanks for the suggestions.

I've fixed the link.

Added Laser Rifle Rebirth, WAP 12.7 SMG Rebirth, WAP Gauss Rifle, WAP Single Shotgun, Euclid's C-Finder Retexture, BB Gun ReTexture.

**Comment by satorope** [comment]
Thanks for the correction, good job.
