### ISSUE TITLE
Weapon Texture Fixes and Bullet Time

### ISSUE THREAD

**Issue by satorope** [mojaveexpressguide/mojaveexpressguide.github.io#3]
I see the salamand3r guide has been updated. That's very good.

There was an error in the last point I made. My apologies.
The "WAP Year One and Bonus" included a Gauss Rifle which was not specified.
So only "WAP Gauss Rifle Texture Edit" is needed.
You also need "Laser Pistol 3rd Person Latch animation fix".

https://www.nexusmods.com/newvegas/mods/80657

Here is a suggestion.
How about removing the "JAM VNV Configuration" to enable the "CyberJam" mod to enhance bullet time and the "JAM or Just Sprint animation replacers" sprint animation?
Also, I think it would be better to mention in the description that Wired Synapses enhance the bullet time. I didn't notice it the first time I played.
There is a problem that JAM's Bullet Time does not reflect the Perk correctly, so the following mods should also be added.

Bullet Time Improved - a JAM addon
https://www.nexusmods.com/newvegas/mods/78324/

PushTheWinButton has created a mod to replace VATS as the "perfect Bullet Time" but unfortunately it is not compatible with "CyberJam".

VATS Alternative - A Comprehensive Bullet Time Mod
https://www.nexusmods.com/newvegas/mods/62278/

**Comment by mojaveexpressguide** [comment]
Thanks a lot for the suggestions.

I've remove the gauss rifle link
Added Laser Pistol 3rd Person Latch animation fix
Also added my own JAM config.
And lastly added Bullet Time Improved - a JAM addon (this was in the guide a while ago I think I just forgot to add it when transfering the website to github.
