### ISSUE TITLE
WAP B42 Optics and  Character Kit Remake

### ISSUE THREAD

**Issue by satorope** [mojaveexpressguide/mojaveexpressguide.github.io#4]
Hello.
You are going your own route on weapon and armor textures, different from salamand3r's texture guide.
WAP B42 Optics Patch needs to be fixed by [B42 Optics NV Patches](https://www.nexusmods.com/newvegas/mods/82136).

I see that VNV Qolore7 has created [Blue Moon](https://qolore7.github.io/bluemoon/).
[Character Kit Remake](https://www.nexusmods.com/newvegas/mods/82145) might be good to use with Character Expansions Revised.
[Character Expansions Revised Character Kit Remake Patch](https://www.nexusmods.com/newvegas/mods/83002)

**Comment by mojaveexpressguide** [comment]
I'm not really going to be updating the texture guides I've created from now on. I have mostly kept them there for archive purposes. In the future I may make a version specifically for my guide. I have thought about adding Character Kit Remake. I'll make a poll in my discord and see what the results are. Personally I thought it looked quite good overall.

**Comment by satorope** [comment]
Okay, I see what you mean. Looking forward to your next update.
